#!/usr/bin/env python
import argparse
import logging
import sys

import os
import gSed.gSwap


logger = logging.getLogger("gSwap")
logger.setLevel(logging.ERROR)
handler_stderr = logging.StreamHandler(sys.stderr)
logger.addHandler(handler_stderr)


def check_arg(args=None):
    """
    Check the arguments passed
    """
    parser = argparse.ArgumentParser(
        description='Script to swap gendered language inside a text stream or file')
    parser.add_argument('-i', '--input',
                        help='Input File instead of STDIN',
                        default='',
                        required=False)
    parser.add_argument('-o', '--output',
                        help='Output File instead of STDOUT',
                        default=None,
                        required=False)
    parser.add_argument('-r', '--results',
                        help='Filename to store swap results in',
                        default='',
                        required=False)
    parser.add_argument('-c', '--context',
                        help='Filename to store context swap results in',
                        default='',
                        required=False)

    results = parser.parse_args(args)
    return results.input, results.output, results.results, results.context


def scan(input_name, output_name, results, context):

    surgeon = gSed.gSwap.gSwap()

    try:
        if input_name and not output_name:
            ext = os.path.splitext(input_name)[-1]
            output_name = input_name.replace(ext, ".gswap{ext}".format(ext=ext))

        # Set Output Stream
        if input_name and output_name:
            with open(input_name, 'r') as input_file:
                content = input_file.readlines()
            with open(output_name, 'w') as output_file:
                for line in content:
                    output_file.writelines(surgeon.swap(line))
        else:
            for line in iter(sys.stdin.readline, b''):
                sys.stdout.writelines(surgeon.swap(line))
    except KeyboardInterrupt:
        sys.stdout.flush()
        pass
    except Exception as ex:
        logging.error(ex)
        return 1

    if results:
        with open(results, 'a') as results_file:
            results_file.write(surgeon.swaps_perfomed())
    if context:
        with open(context, 'a') as context_file:
            context_file.write(surgeon.contexts_performed())

    return 0


if __name__ == '__main__':
    exit(scan(*check_arg()))
